### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nelsonic**
Last one for the day. :+1:

### CODE REVIEW

**Comment by iteles** [comment]
@rjmk Look who checks his notifications now!

**Comment by rjmk** [comment]
@iteles Vanity emails ... :lipstick:

**Comment by nelsonic** [comment]
Good old Bes... :wink: 
Night guys. :+1: 
:heart: u both!
https://twitter.com/iamdevloper/status/585066879221370880

**Comment by rjmk** [comment]
:heart: :sleeping:

**Pull request merged**
